# Use this to pipe 'hello world' etc in through curl and see it in stdout.
# command: curl http://localhost:1234/post -d "hello world"
input:
  type: http_server
  http_server:
    address: "localhost:8080"
    path: "/post"
    timeout_ms: 1000
output:
  type: zmq4
  zmq4:
    addresses:
      - tcp://*:1235
    socket_type: PUSH
