output:
  type: fan_out
  fan_out:
    outputs:
    - type: nats
      nats:
        url: nats://localhost:4222
        subject: benthos_messages
    - type: ditto
      nats:
        url: nats://localhost:4222
        subject: benthos_messages_2
