input:
  type: fan_in
  fan_in:
    inputs: [
      {
        "type": "nats",
        "nats": {
          "url": "nats://localhost:4222",
          "subject": "benthos_messages"
        }
      },
      {
        "type": "ditto",
        "nats": {
          "url": "nats://localhost:4222",
          "subject": "benthos_messages_2"
        }
      }
    ]
