input:
  type: nats_stream
  nats_stream:
    url: nats://localhost:4222
    cluster_id: test-cluster
    client_id: benthos_client_1
    queue: benthos_queue
    durable_name: benthos_offset
    subject: benthos_messages
output:
  type: nats_stream
  nats_stream:
    url: nats://localhost:4222
    cluster_id: test-cluster
    client_id: benthos_client_2
    subject: benthos_messages
