input:
  type: nsq
  nsq:
    nsqd_tcp_addresses:
    - 127.0.0.1:4150
    lookupd_http_addresses:
    - 127.0.0.1:4161
    topic: benthos_messages
    channel: benthos_stream
    user_agent: benthos_consumer
    max_in_flight: 100
output:
  type: nsq
  nsq:
    nsqd_tcp_address: 127.0.0.1:4150
    topic: benthos_messages
    user_agent: benthos_producer
    max_in_flight: 100
