input:
  type: fan_in
  fan_in:
    inputs:
      -
        type: http_server
        http_server:
          address: localhost:8080
          path: /post
      -
        type: scalability_protocols
        scalability_protocols:
          address: tcp://localhost:5555
          bind_address: true
          socket_type: PULL
      -
        type: zmq4
        zmq4:
          addresses:
          - tcp://*:5556
          socket_type: PULL
      -
        type: kafka
        kafka:
          addresses:
          - localhost:9092
          client_id: benthos_kafka_input
          consumer_group: benthos_consumer_group
          topic: benthos_stream
          partition: 0
          start_from_oldest: true
output:
  type: stdout
logger:
  log_level: DEBUG
